### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by CodeGuyPaul** [Regentmango7/software_engineering_project#6]
<img width="820" alt="Screen Shot 2022-11-12 at 10 29 17 PM" src="https://user-images.githubusercontent.com/93624452/201504231-7ba19d20-a225-4e4a-be25-e70845325b9e.png">

        self.coin.setAmount(data["Coins"])
This line of code seems to not be able to find an entry called coins in data

**Comment by CodeGuyPaul** [comment]
I think save() should be called before line 181. however, I do not understand the code well enough to know exactly what to do

if os.path.exists("./local_data.json"):
    with open("./local_data.json", "r") as file:
        gameData.dataLoad(json.load(file))

**Comment by CodeGuyPaul** [comment]
I think I fixed it by putting save() before line 181

**Comment by Regentmango7** [comment]
you had to remove the save file you had which was old.
